apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-redis
spec:
  replicas: {{ .Values.redis.deployment.replicas }}
  selector:
    matchLabels:
      app: ckan-redis
  template:
    metadata:
      labels:
        app: ckan-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.deployment.image }}
          args:
            - redis-server
            - --save ""
            - --appendonly no
            - --bind 0.0.0.0
            - --protected-mode no
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: ckan-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: ckan-redis