apiVersion: v1
kind: ConfigMap
metadata:
  name: ckan-worker-config
data:
  {{- /* First: include all CKAN base env vars */}}
  {{- range $key, $value := .Values.ckan.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  {{- /* Second: include all CKAN worker-specific env vars */}}
  {{- range $key, $value := .Values.ckan-worker.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  